### ISSUE TITLE
Unhandled exception. System.IO.IOException: The process cannot access the file

### ISSUE THREAD

**Issue by WangYu0611** [OpenDroneMap/Obj2Tiles#48]
?> Loaded 3829944 vertices, 1758548 faces in 4727ms
 -> Splitting with a depth of 1
 ?> Done 22249 edge splits in 3891ms (5.72 split/ms)
 -> Writing tiles
 !> Exception: Index was outside the bounds of the array.

 => Pipeline completed in 00:48:46.2553339
 => Cleaning up
Unhandled exception. System.IO.IOException: The process cannot access the file 'Mesh-XL-YL-texture-SimplygonCastMaterial_016.jpg' because it is being used by another process.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String, WIN32_FIND_DATA&, Boolean)
   at System.IO.FileSystem.RemoveDirectory(String, Boolean)
   at Obj2Tiles.Program.Run(Options opts)
   at CommandLine.ParserResultExtensions.WithParsedAsync[T](ParserResult`1 result, Func`2 action)
   at Obj2Tiles.Program.Main(String[] args)
   at Obj2Tiles.Program.<Main>(String[] args)

**Comment by HeDo88TH** [comment]
If you are still encountering this, link the file and reopen the issue.
